---
extends: stylelint-config-standard-scss
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - use
        - function
        - if
        - each
        - include
        - mixin
        - at-root
  block-no-empty:
  color-function-notation:
  color-hex-length: long
  color-no-invalid-hex: true
  comment-empty-line-before:
    - always
    - ignore:
        - stylelint-commands
        - after-comment
  declaration-colon-newline-after:
  declaration-colon-space-after: always
  font-family-no-missing-generic-family-keyword:
  indentation: 4
  max-empty-lines: 2
  max-line-length:
    - 120
    - ignore:
        - comments
  property-no-vendor-prefix:
  rule-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - after-comment
  scss/at-mixin-argumentless-call-parentheses:
  scss/at-mixin-pattern:
    - '^[a-z][a-zA-Z0-9]+$'
    - message: Expected mixin name to be lowerCamelCase
  scss/double-slash-comment-empty-line-before:
  # Use the standard rule for these (kebab-case)
  #scss/dollar-variable-pattern:
  #selector-class-pattern:
  #selector-id-pattern:
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - global
        - local
  string-quotes: single
  unit-allowed-list:
    - em
    - rem
    - pt
    - %
    - s
    - px
    - vh
    - vw
    - deg
    - fr
  value-no-vendor-prefix:
